name: Preview Deploy
on: [push]
jobs:
  deploying:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip deploy]')"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        preview_prefix: 'yc-tw-theme'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - run: npm run preview:build

      - name: Surge Deploy
        env:
          PROJECT_NAME: ${{ matrix.preview_prefix }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: npm run preview:deploy

      - name: Add comment to Pull Request
        if: github.ref != 'refs/heads/master'
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ format('Your preview application is ready in http://{1}-{0}.surge.sh', steps.extract_branch.outputs.branch, matrix.preview_prefix) }}
          check_for_duplicate_msg: true
